/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MainController */

#ifndef _Included_main_MainController
#define _Included_main_MainController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_MainController
 * Method:    getComPorts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_main_MainController_getComPorts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
